#!/usr/bin/env python3
"""Page - A minimal fullscreen single-page web browser."""

import sys
import gi

gi.require_version("Gtk", "3.0")
gi.require_version("WebKit2", "4.1")
from gi.repository import Gtk, WebKit2


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <url>", file=sys.stderr)
        sys.exit(1)

    url = sys.argv[1]
    if not url.startswith(("http://", "https://", "file://")):
        url = "https://" + url

    win = Gtk.Window()
    win.set_title("Page")
    win.connect("destroy", Gtk.main_quit)
    win.fullscreen()

    webview = WebKit2.WebView()

    # Minimize resource usage
    settings = webview.get_settings()
    settings.set_enable_smooth_scrolling(False)
    settings.set_hardware_acceleration_policy(
        WebKit2.HardwareAccelerationPolicy.NEVER
    )

    webview.load_uri(url)
    win.add(webview)
    win.show_all()
    Gtk.main()


if __name__ == "__main__":
    main()
